services:
    Chang\Menu\YamlMenu:
        autowire: true
        tags: [kernel.event_subscriber]

    Chang\Menu\YamlMenuResolverInterface:
        class: Chang\Menu\YamlMenuResolver
        autowire: true
