parameters:
    chang.packages.geo_ip.compilers:
        - Chang\GeoIp\Compiler\AdapterCompilePass
    chang.packages.geo_ip.data_source:
        adapter: chang.geo_ip.db_adapter
    chang.packages.geo_ip.db_adapter:
        db_file: ~
    chang.packages.geo_ip.ipstack_adapter:
        access_key: ~

services:
    Chang\GeoIp\DataSource:
        autowire: true

    chang.geo_ip.db_adapter:
        class: Chang\GeoIp\GeoIP2DBAdapter
        arguments:
        - '@=service("chang.option_resolver").get("geo_ip.db_adapter.db_file")'

    chang.geo_ip.ipstack_adapter:
        class: Chang\GeoIp\IpStackAdapter
        arguments:
        - '@=service("chang.option_resolver").get("geo_ip.ipstack_adapter.access_key")'
