parameters:
    chang.packages.secure_area.password_confirm:
        template: ~
        password_parameter: _password
        lifetime: +15 minutes
        patterns: []

services:
    Chang\SecureArea\UserPasswordCheckerInterface:
        alias: chang.secure_area.user_password_checker

    chang.secure_area.user_password_checker:
        class: Chang\SecureArea\UserPasswordChecker
        arguments:
            - '@security.token_storage'
            - '@security.encoder_factory'

    chang.secure_area.access_listener:
        class: Chang\SecureArea\AccessListener
        tags: [{ name: kernel.event_subscriber }]
        arguments:
            - '@chang.secure_area.user_password_checker'
            - '@templating'
            - '@session'
            - '@=service("chang.option_resolver").get("secure_area.password_confirm")'
