parameters:
    chang.packages.user.verify_email_change:
        enabled: false

imports:
    - ./services/*

framework:
    validation:
        mapping:
            paths:
                - '%chang.dir%/User/Resources/config/validation'
    translator:
        paths:
            - '%chang.dir%/User/Resources/translations'

## Why user change **NEED** DTO? ##
# - https://github.com/symfony/symfony/issues/13870
# - https://github.com/symfony/symfony/issues/12025
##
