sylius_grid:
    grids:
        security_audit_grid:
            driver:
                options:
                    class: "%chang.model.security_audit_login.class%"
            limits: [10]
            sorting:
                loginAt: desc
            fields:
                sessionId:
                    type: text
                    label: chang.ui.security_audit.session_id
                loginAt:
                    type: localizeddate
                    label: chang.ui.security_audit.login_at
                    sortable: ~
                logoutAt:
                    type: localizeddate
                    label: chang.ui.security_audit.logout_at
                    sortable: ~
                location:
                    type: tpl
                    label: chang.ui.security_audit.location
                    path: .
