parameters:
    chang.packages.security.password_strength:
        algorithm: zxcvbn
        score: 1
        options: []

services:
    Chang\Security\Validator\PasswordStrength\ConstraintValidator:
        tags: [{ name: validator.constraint_validator, alias: password_strength_validator }]
        arguments:
            - '@=service("chang.option_resolver").get("security.password_strength.algorithm")'
            - '@=service("chang.option_resolver").get("security.password_strength.score")'
            - '@=service("chang.option_resolver").get("security.password_strength.options")'

framework:
    translator:
        paths:
            - '%chang.dir%/Security/Resources/translations'
    validation:
        mapping:
            paths:
                - '%chang.dir%/Security/Resources/config/validation'
